spring:
   application:
      name: lcodedataservice
   jpa:
      database-platform: org.hibernate.dialect.Oracle10gDialect
      show-sql: true
      hibernate:
          generate_statistics: true
   datasource: 
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@(DESCRIPTION_LIST=(LOAD_BALANCE=OFF)(FAILOVER=YES)(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=uklpdudasa-scan.uk.standardchartered.com)(PORT=1622)))(CONNECT_DATA=(SERVICE_NAME=CRMATE_PT.uk.standardchartered.com))))
      username: CRMATE_PT_01
      password: CRMATE_PT_01_123
      main:
        allow-bean-definition-overriding: true   
            
server:
   port: 8091
info:
   app:
      name: lcodedataservice Application
    version: 1.0.0
   
limits:
  - default:
      memory: 1Gi
    defaultRequest:
      memory: 1Gi
    max:
      memory: 1Gi
    min:
      memory: 500Mi
    type: Container
     